/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface ArtistProfile {
  'bio' : string,
  'instagram' : string,
  'buyMeACoffee' : string,
  'youtube' : string,
}
export interface Attachment {
  'blob' : ExternalBlob,
  'mimeType' : string,
  'fileName' : string,
}
export interface ContactInfo {
  'instagram' : string,
  'name' : string,
  'email' : string,
  'youtube' : string,
  'phone' : string,
}
export type ExternalBlob = Uint8Array;
export interface Message {
  'id' : bigint,
  'content' : string,
  'audioAttachment' : [] | [Attachment],
  'pdfAttachment' : [] | [Attachment],
  'isRead' : boolean,
  'sender' : string,
  'imageAttachment' : [] | [Attachment],
  'fileAttachment' : [] | [Attachment],
  'timestamp' : bigint,
  'isAdmin' : boolean,
  'recipientSeen' : boolean,
}
export interface MessagesView {
  'contactInfo' : [] | [ContactInfo],
  'messages' : Array<Message>,
}
export interface PlaylistView { 'name' : string, 'songIds' : Array<bigint> }
export interface SongView {
  'id' : bigint,
  'albumArt' : ExternalBlob,
  'title' : string,
  'lyrics' : string,
  'owner' : Principal,
  'audioFile' : ExternalBlob,
  'playCount' : bigint,
  'artist' : string,
  'likesCount' : bigint,
  'titleImage' : ExternalBlob,
}
export interface UserProfileRecord {
  'totalListeningTime' : bigint,
  'userName' : string,
  'dateOfBirth' : string,
  'fullName' : string,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addListeningTime' : ActorMethod<[bigint], undefined>,
  'addSong' : ActorMethod<
    [string, string, ExternalBlob, ExternalBlob, ExternalBlob, string, string],
    bigint
  >,
  'addToOfficialPlaylist' : ActorMethod<[string, bigint, string], undefined>,
  'addToPlaylist' : ActorMethod<[string, bigint], undefined>,
  'adminDeleteConversation' : ActorMethod<
    [[] | [string], string, string],
    undefined
  >,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'checkAuthorization' : ActorMethod<[], boolean>,
  'clearFavorites' : ActorMethod<[], undefined>,
  'clearMessages' : ActorMethod<[], undefined>,
  'createOfficialPlaylist' : ActorMethod<[string, string], undefined>,
  'createPlaylist' : ActorMethod<[string], undefined>,
  'deleteMessage' : ActorMethod<[bigint], undefined>,
  'deletePlaylist' : ActorMethod<[string, [] | [string]], undefined>,
  'deleteSong' : ActorMethod<[bigint, string], undefined>,
  'deleteUserMessage' : ActorMethod<[Principal, bigint, string], undefined>,
  'getAllConversations' : ActorMethod<[string], Array<Principal>>,
  'getAllConversationsByUserIdPasscode' : ActorMethod<
    [string],
    Array<Principal>
  >,
  'getAllMessages' : ActorMethod<[Principal, string], [] | [MessagesView]>,
  'getAllSongs' : ActorMethod<[], Array<SongView>>,
  'getAllSongsByTitle' : ActorMethod<[], Array<SongView>>,
  'getArtistProfile' : ActorMethod<[], ArtistProfile>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfileRecord]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getFavorites' : ActorMethod<[], Array<bigint>>,
  'getHiddenAdminModeStatus' : ActorMethod<[string], boolean>,
  'getMessages' : ActorMethod<[], [] | [MessagesView]>,
  'getOfficialPlaylist' : ActorMethod<[string], [] | [PlaylistView]>,
  'getOfficialPlaylistDetails' : ActorMethod<[string], Array<SongView>>,
  'getPlaylist' : ActorMethod<[string], PlaylistView>,
  'getPlaylistDetails' : ActorMethod<[string], Array<SongView>>,
  'getPlaylistFavorites' : ActorMethod<[], Array<string>>,
  'getPlaylistFavoritesLegacy' : ActorMethod<[], Array<string>>,
  'getSong' : ActorMethod<[bigint], SongView>,
  'getTotalListeningTime' : ActorMethod<[], bigint>,
  'getUnreadMessagesCount' : ActorMethod<[string], bigint>,
  'getUserPlaylists' : ActorMethod<[], Array<PlaylistView>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfileRecord]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'isPlaylistFavorite' : ActorMethod<[string], boolean>,
  'listOfficialPlaylists' : ActorMethod<[], Array<PlaylistView>>,
  'markAllMessagesAsSeen' : ActorMethod<[string, Principal, string], undefined>,
  'markLastMessageAsRead' : ActorMethod<[], undefined>,
  'markMessagesAsSeen' : ActorMethod<[boolean], undefined>,
  'playSong' : ActorMethod<[bigint], undefined>,
  'playlistFavoritesLegacy' : ActorMethod<[], [] | [Array<string>]>,
  'removeFromOfficialPlaylist' : ActorMethod<
    [string, bigint, string],
    undefined
  >,
  'removeFromPlaylist' : ActorMethod<[string, bigint], undefined>,
  'reorderOfficialPlaylist' : ActorMethod<
    [string, Array<bigint>, string],
    undefined
  >,
  'reorderPlaylist' : ActorMethod<[string, Array<bigint>], undefined>,
  'replyToMessage' : ActorMethod<[Principal, string, string], bigint>,
  'replyWithAttachments' : ActorMethod<
    [
      Principal,
      string,
      [] | [Attachment],
      [] | [Attachment],
      [] | [Attachment],
      [] | [Attachment],
      string,
    ],
    bigint
  >,
  'saveCallerUserProfile' : ActorMethod<[UserProfileRecord], undefined>,
  'searchSongs' : ActorMethod<[string], Array<SongView>>,
  'sendMessage' : ActorMethod<[string], bigint>,
  'sendMessageWithAttachments' : ActorMethod<
    [
      string,
      [] | [Attachment],
      [] | [Attachment],
      [] | [Attachment],
      [] | [Attachment],
    ],
    bigint
  >,
  'setHiddenAdminMode' : ActorMethod<[boolean, string], undefined>,
  'toggleFavorite' : ActorMethod<[bigint], boolean>,
  'toggleLikeSong' : ActorMethod<[bigint], bigint>,
  'togglePlaylistFavorite' : ActorMethod<[string], boolean>,
  'updateAdminInfo' : ActorMethod<[[] | [ContactInfo], string], undefined>,
  'updateArtistProfile' : ActorMethod<[ArtistProfile, string], undefined>,
  'updateTotalListeningTime' : ActorMethod<[bigint], undefined>,
  'verifyAdminPasscodeForHiddenAdminMode' : ActorMethod<[string], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];