/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type ExternalBlob = Uint8Array;
export interface PlaylistView { 'name' : string, 'songIds' : Array<bigint> }
export interface SongView {
  'id' : bigint,
  'albumArt' : ExternalBlob,
  'title' : string,
  'lyrics' : string,
  'owner' : Principal,
  'audioFile' : ExternalBlob,
  'playCount' : bigint,
  'artist' : string,
  'likesCount' : bigint,
  'titleImage' : ExternalBlob,
}
export interface UserProfile { 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addSong' : ActorMethod<
    [string, string, ExternalBlob, ExternalBlob, ExternalBlob, string, string],
    bigint
  >,
  'addToOfficialPlaylist' : ActorMethod<[string, bigint, string], undefined>,
  'addToPlaylist' : ActorMethod<[string, bigint], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'checkAuthorization' : ActorMethod<[], boolean>,
  'clearFavorites' : ActorMethod<[], undefined>,
  'createOfficialPlaylist' : ActorMethod<[string, string], undefined>,
  'createPlaylist' : ActorMethod<[string], undefined>,
  'deleteSong' : ActorMethod<[bigint, string], undefined>,
  'getAllSongs' : ActorMethod<[], Array<SongView>>,
  'getAllSongsByTitle' : ActorMethod<[], Array<SongView>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getFavorites' : ActorMethod<[], Array<bigint>>,
  'getOfficialPlaylist' : ActorMethod<[string], [] | [PlaylistView]>,
  'getOfficialPlaylistDetails' : ActorMethod<[string], Array<SongView>>,
  'getPlaylist' : ActorMethod<[string], PlaylistView>,
  'getPlaylistDetails' : ActorMethod<[string], Array<SongView>>,
  'getSong' : ActorMethod<[bigint], SongView>,
  'getUserPlaylists' : ActorMethod<[], Array<PlaylistView>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'listOfficialPlaylists' : ActorMethod<[], Array<PlaylistView>>,
  'playSong' : ActorMethod<[bigint], undefined>,
  'removeFromOfficialPlaylist' : ActorMethod<
    [string, bigint, string],
    undefined
  >,
  'removeFromPlaylist' : ActorMethod<[string, bigint], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'searchSongs' : ActorMethod<[string], Array<SongView>>,
  'toggleFavorite' : ActorMethod<[bigint], boolean>,
  'toggleLikeSong' : ActorMethod<[bigint], bigint>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];