/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const ExternalBlob = IDL.Vec(IDL.Nat8);
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const ContactInfo = IDL.Record({
  'instagram' : IDL.Text,
  'name' : IDL.Text,
  'email' : IDL.Text,
  'youtube' : IDL.Text,
  'phone' : IDL.Text,
});
export const Message = IDL.Record({
  'id' : IDL.Nat,
  'content' : IDL.Text,
  'audioAttachment' : IDL.Opt(ExternalBlob),
  'pdfAttachment' : IDL.Opt(ExternalBlob),
  'isRead' : IDL.Bool,
  'sender' : IDL.Text,
  'imageAttachment' : IDL.Opt(ExternalBlob),
  'timestamp' : IDL.Int,
  'isAdmin' : IDL.Bool,
  'recipientSeen' : IDL.Bool,
});
export const MessagesView = IDL.Record({
  'contactInfo' : IDL.Opt(ContactInfo),
  'messages' : IDL.Vec(Message),
});
export const SongView = IDL.Record({
  'id' : IDL.Nat,
  'albumArt' : ExternalBlob,
  'title' : IDL.Text,
  'lyrics' : IDL.Text,
  'owner' : IDL.Principal,
  'audioFile' : ExternalBlob,
  'playCount' : IDL.Nat,
  'artist' : IDL.Text,
  'likesCount' : IDL.Nat,
  'titleImage' : ExternalBlob,
});
export const ArtistProfile = IDL.Record({
  'bio' : IDL.Text,
  'instagram' : IDL.Text,
  'buyMeACoffee' : IDL.Text,
  'youtube' : IDL.Text,
});
export const UserProfileRecord = IDL.Record({
  'totalListeningTime' : IDL.Nat,
  'userName' : IDL.Text,
  'dateOfBirth' : IDL.Text,
  'fullName' : IDL.Text,
});
export const PlaylistView = IDL.Record({
  'name' : IDL.Text,
  'songIds' : IDL.Vec(IDL.Nat),
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addListeningTime' : IDL.Func([IDL.Nat], [], []),
  'addSong' : IDL.Func(
      [
        IDL.Text,
        IDL.Text,
        ExternalBlob,
        ExternalBlob,
        ExternalBlob,
        IDL.Text,
        IDL.Text,
      ],
      [IDL.Nat],
      [],
    ),
  'addToOfficialPlaylist' : IDL.Func([IDL.Text, IDL.Nat, IDL.Text], [], []),
  'addToPlaylist' : IDL.Func([IDL.Text, IDL.Nat], [], []),
  'adminDeleteConversation' : IDL.Func(
      [IDL.Opt(IDL.Text), IDL.Text, IDL.Text],
      [],
      [],
    ),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'checkAuthorization' : IDL.Func([], [IDL.Bool], ['query']),
  'clearFavorites' : IDL.Func([], [], []),
  'clearMessages' : IDL.Func([], [], []),
  'createOfficialPlaylist' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'createPlaylist' : IDL.Func([IDL.Text], [], []),
  'deleteMessage' : IDL.Func([IDL.Nat], [], []),
  'deletePlaylist' : IDL.Func([IDL.Text, IDL.Opt(IDL.Text)], [], []),
  'deleteSong' : IDL.Func([IDL.Nat, IDL.Text], [], []),
  'deleteUserMessage' : IDL.Func([IDL.Principal, IDL.Nat, IDL.Text], [], []),
  'getAllConversations' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(IDL.Principal)],
      ['query'],
    ),
  'getAllConversationsByUserIdPasscode' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(IDL.Principal)],
      ['query'],
    ),
  'getAllMessages' : IDL.Func(
      [IDL.Principal, IDL.Text],
      [IDL.Opt(MessagesView)],
      ['query'],
    ),
  'getAllSongs' : IDL.Func([], [IDL.Vec(SongView)], ['query']),
  'getAllSongsByTitle' : IDL.Func([], [IDL.Vec(SongView)], ['query']),
  'getArtistProfile' : IDL.Func([], [ArtistProfile], ['query']),
  'getCallerUserProfile' : IDL.Func(
      [],
      [IDL.Opt(UserProfileRecord)],
      ['query'],
    ),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getFavorites' : IDL.Func([], [IDL.Vec(IDL.Nat)], ['query']),
  'getHiddenAdminModeStatus' : IDL.Func([IDL.Text], [IDL.Bool], ['query']),
  'getMessages' : IDL.Func([], [IDL.Opt(MessagesView)], ['query']),
  'getOfficialPlaylist' : IDL.Func(
      [IDL.Text],
      [IDL.Opt(PlaylistView)],
      ['query'],
    ),
  'getOfficialPlaylistDetails' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(SongView)],
      ['query'],
    ),
  'getPlaylist' : IDL.Func([IDL.Text], [PlaylistView], ['query']),
  'getPlaylistDetails' : IDL.Func([IDL.Text], [IDL.Vec(SongView)], ['query']),
  'getSong' : IDL.Func([IDL.Nat], [SongView], ['query']),
  'getTotalListeningTime' : IDL.Func([], [IDL.Nat], ['query']),
  'getUnreadMessagesCount' : IDL.Func([IDL.Text], [IDL.Nat], []),
  'getUserPlaylists' : IDL.Func([], [IDL.Vec(PlaylistView)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfileRecord)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'listOfficialPlaylists' : IDL.Func([], [IDL.Vec(PlaylistView)], ['query']),
  'markAllMessagesAsSeen' : IDL.Func(
      [IDL.Text, IDL.Principal, IDL.Text],
      [],
      [],
    ),
  'markLastMessageAsRead' : IDL.Func([], [], []),
  'markMessagesAsSeen' : IDL.Func([IDL.Bool], [], []),
  'playSong' : IDL.Func([IDL.Nat], [], []),
  'removeFromOfficialPlaylist' : IDL.Func(
      [IDL.Text, IDL.Nat, IDL.Text],
      [],
      [],
    ),
  'removeFromPlaylist' : IDL.Func([IDL.Text, IDL.Nat], [], []),
  'replyToMessage' : IDL.Func(
      [IDL.Principal, IDL.Text, IDL.Text],
      [IDL.Nat],
      [],
    ),
  'replyWithAttachments' : IDL.Func(
      [
        IDL.Principal,
        IDL.Text,
        IDL.Opt(ExternalBlob),
        IDL.Opt(ExternalBlob),
        IDL.Opt(ExternalBlob),
        IDL.Text,
      ],
      [IDL.Nat],
      [],
    ),
  'saveCallerUserProfile' : IDL.Func([UserProfileRecord], [], []),
  'searchSongs' : IDL.Func([IDL.Text], [IDL.Vec(SongView)], ['query']),
  'sendMessage' : IDL.Func([IDL.Text], [IDL.Nat], []),
  'sendMessageWithAttachments' : IDL.Func(
      [
        IDL.Text,
        IDL.Opt(ExternalBlob),
        IDL.Opt(ExternalBlob),
        IDL.Opt(ExternalBlob),
      ],
      [IDL.Nat],
      [],
    ),
  'setHiddenAdminMode' : IDL.Func([IDL.Bool, IDL.Text], [], []),
  'toggleFavorite' : IDL.Func([IDL.Nat], [IDL.Bool], []),
  'toggleLikeSong' : IDL.Func([IDL.Nat], [IDL.Nat], []),
  'updateAdminInfo' : IDL.Func([IDL.Opt(ContactInfo)], [], []),
  'updateArtistProfile' : IDL.Func([ArtistProfile], [], []),
  'updateTotalListeningTime' : IDL.Func([IDL.Nat], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const ContactInfo = IDL.Record({
    'instagram' : IDL.Text,
    'name' : IDL.Text,
    'email' : IDL.Text,
    'youtube' : IDL.Text,
    'phone' : IDL.Text,
  });
  const Message = IDL.Record({
    'id' : IDL.Nat,
    'content' : IDL.Text,
    'audioAttachment' : IDL.Opt(ExternalBlob),
    'pdfAttachment' : IDL.Opt(ExternalBlob),
    'isRead' : IDL.Bool,
    'sender' : IDL.Text,
    'imageAttachment' : IDL.Opt(ExternalBlob),
    'timestamp' : IDL.Int,
    'isAdmin' : IDL.Bool,
    'recipientSeen' : IDL.Bool,
  });
  const MessagesView = IDL.Record({
    'contactInfo' : IDL.Opt(ContactInfo),
    'messages' : IDL.Vec(Message),
  });
  const SongView = IDL.Record({
    'id' : IDL.Nat,
    'albumArt' : ExternalBlob,
    'title' : IDL.Text,
    'lyrics' : IDL.Text,
    'owner' : IDL.Principal,
    'audioFile' : ExternalBlob,
    'playCount' : IDL.Nat,
    'artist' : IDL.Text,
    'likesCount' : IDL.Nat,
    'titleImage' : ExternalBlob,
  });
  const ArtistProfile = IDL.Record({
    'bio' : IDL.Text,
    'instagram' : IDL.Text,
    'buyMeACoffee' : IDL.Text,
    'youtube' : IDL.Text,
  });
  const UserProfileRecord = IDL.Record({
    'totalListeningTime' : IDL.Nat,
    'userName' : IDL.Text,
    'dateOfBirth' : IDL.Text,
    'fullName' : IDL.Text,
  });
  const PlaylistView = IDL.Record({
    'name' : IDL.Text,
    'songIds' : IDL.Vec(IDL.Nat),
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addListeningTime' : IDL.Func([IDL.Nat], [], []),
    'addSong' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          ExternalBlob,
          ExternalBlob,
          ExternalBlob,
          IDL.Text,
          IDL.Text,
        ],
        [IDL.Nat],
        [],
      ),
    'addToOfficialPlaylist' : IDL.Func([IDL.Text, IDL.Nat, IDL.Text], [], []),
    'addToPlaylist' : IDL.Func([IDL.Text, IDL.Nat], [], []),
    'adminDeleteConversation' : IDL.Func(
        [IDL.Opt(IDL.Text), IDL.Text, IDL.Text],
        [],
        [],
      ),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'checkAuthorization' : IDL.Func([], [IDL.Bool], ['query']),
    'clearFavorites' : IDL.Func([], [], []),
    'clearMessages' : IDL.Func([], [], []),
    'createOfficialPlaylist' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'createPlaylist' : IDL.Func([IDL.Text], [], []),
    'deleteMessage' : IDL.Func([IDL.Nat], [], []),
    'deletePlaylist' : IDL.Func([IDL.Text, IDL.Opt(IDL.Text)], [], []),
    'deleteSong' : IDL.Func([IDL.Nat, IDL.Text], [], []),
    'deleteUserMessage' : IDL.Func([IDL.Principal, IDL.Nat, IDL.Text], [], []),
    'getAllConversations' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(IDL.Principal)],
        ['query'],
      ),
    'getAllConversationsByUserIdPasscode' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(IDL.Principal)],
        ['query'],
      ),
    'getAllMessages' : IDL.Func(
        [IDL.Principal, IDL.Text],
        [IDL.Opt(MessagesView)],
        ['query'],
      ),
    'getAllSongs' : IDL.Func([], [IDL.Vec(SongView)], ['query']),
    'getAllSongsByTitle' : IDL.Func([], [IDL.Vec(SongView)], ['query']),
    'getArtistProfile' : IDL.Func([], [ArtistProfile], ['query']),
    'getCallerUserProfile' : IDL.Func(
        [],
        [IDL.Opt(UserProfileRecord)],
        ['query'],
      ),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getFavorites' : IDL.Func([], [IDL.Vec(IDL.Nat)], ['query']),
    'getHiddenAdminModeStatus' : IDL.Func([IDL.Text], [IDL.Bool], ['query']),
    'getMessages' : IDL.Func([], [IDL.Opt(MessagesView)], ['query']),
    'getOfficialPlaylist' : IDL.Func(
        [IDL.Text],
        [IDL.Opt(PlaylistView)],
        ['query'],
      ),
    'getOfficialPlaylistDetails' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(SongView)],
        ['query'],
      ),
    'getPlaylist' : IDL.Func([IDL.Text], [PlaylistView], ['query']),
    'getPlaylistDetails' : IDL.Func([IDL.Text], [IDL.Vec(SongView)], ['query']),
    'getSong' : IDL.Func([IDL.Nat], [SongView], ['query']),
    'getTotalListeningTime' : IDL.Func([], [IDL.Nat], ['query']),
    'getUnreadMessagesCount' : IDL.Func([IDL.Text], [IDL.Nat], []),
    'getUserPlaylists' : IDL.Func([], [IDL.Vec(PlaylistView)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfileRecord)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'listOfficialPlaylists' : IDL.Func([], [IDL.Vec(PlaylistView)], ['query']),
    'markAllMessagesAsSeen' : IDL.Func(
        [IDL.Text, IDL.Principal, IDL.Text],
        [],
        [],
      ),
    'markLastMessageAsRead' : IDL.Func([], [], []),
    'markMessagesAsSeen' : IDL.Func([IDL.Bool], [], []),
    'playSong' : IDL.Func([IDL.Nat], [], []),
    'removeFromOfficialPlaylist' : IDL.Func(
        [IDL.Text, IDL.Nat, IDL.Text],
        [],
        [],
      ),
    'removeFromPlaylist' : IDL.Func([IDL.Text, IDL.Nat], [], []),
    'replyToMessage' : IDL.Func(
        [IDL.Principal, IDL.Text, IDL.Text],
        [IDL.Nat],
        [],
      ),
    'replyWithAttachments' : IDL.Func(
        [
          IDL.Principal,
          IDL.Text,
          IDL.Opt(ExternalBlob),
          IDL.Opt(ExternalBlob),
          IDL.Opt(ExternalBlob),
          IDL.Text,
        ],
        [IDL.Nat],
        [],
      ),
    'saveCallerUserProfile' : IDL.Func([UserProfileRecord], [], []),
    'searchSongs' : IDL.Func([IDL.Text], [IDL.Vec(SongView)], ['query']),
    'sendMessage' : IDL.Func([IDL.Text], [IDL.Nat], []),
    'sendMessageWithAttachments' : IDL.Func(
        [
          IDL.Text,
          IDL.Opt(ExternalBlob),
          IDL.Opt(ExternalBlob),
          IDL.Opt(ExternalBlob),
        ],
        [IDL.Nat],
        [],
      ),
    'setHiddenAdminMode' : IDL.Func([IDL.Bool, IDL.Text], [], []),
    'toggleFavorite' : IDL.Func([IDL.Nat], [IDL.Bool], []),
    'toggleLikeSong' : IDL.Func([IDL.Nat], [IDL.Nat], []),
    'updateAdminInfo' : IDL.Func([IDL.Opt(ContactInfo)], [], []),
    'updateArtistProfile' : IDL.Func([ArtistProfile], [], []),
    'updateTotalListeningTime' : IDL.Func([IDL.Nat], [], []),
  });
};

export const init = ({ IDL }) => { return []; };