/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const ExternalBlob = IDL.Vec(IDL.Nat8);
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const SongView = IDL.Record({
  'id' : IDL.Nat,
  'albumArt' : ExternalBlob,
  'title' : IDL.Text,
  'lyrics' : IDL.Text,
  'owner' : IDL.Principal,
  'audioFile' : ExternalBlob,
  'playCount' : IDL.Nat,
  'artist' : IDL.Text,
  'likesCount' : IDL.Nat,
  'titleImage' : ExternalBlob,
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });
export const PlaylistView = IDL.Record({
  'name' : IDL.Text,
  'songIds' : IDL.Vec(IDL.Nat),
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addSong' : IDL.Func(
      [IDL.Text, IDL.Text, ExternalBlob, ExternalBlob, ExternalBlob, IDL.Text],
      [IDL.Nat],
      [],
    ),
  'addToOfficialPlaylist' : IDL.Func([IDL.Text, IDL.Nat], [], []),
  'addToPlaylist' : IDL.Func([IDL.Text, IDL.Nat], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'clearFavorites' : IDL.Func([], [], []),
  'createOfficialPlaylist' : IDL.Func([IDL.Text], [], []),
  'createPlaylist' : IDL.Func([IDL.Text], [], []),
  'deleteSong' : IDL.Func([IDL.Nat], [], []),
  'getAllSongs' : IDL.Func([], [IDL.Vec(SongView)], ['query']),
  'getAllSongsByTitle' : IDL.Func([], [IDL.Vec(SongView)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getFavorites' : IDL.Func([], [IDL.Vec(IDL.Nat)], ['query']),
  'getOfficialPlaylist' : IDL.Func(
      [IDL.Text],
      [IDL.Opt(PlaylistView)],
      ['query'],
    ),
  'getOfficialPlaylistDetails' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(SongView)],
      ['query'],
    ),
  'getPlaylist' : IDL.Func([IDL.Text], [PlaylistView], ['query']),
  'getPlaylistDetails' : IDL.Func([IDL.Text], [IDL.Vec(SongView)], ['query']),
  'getSong' : IDL.Func([IDL.Nat], [SongView], ['query']),
  'getUserPlaylists' : IDL.Func([], [IDL.Vec(PlaylistView)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'playSong' : IDL.Func([IDL.Nat], [], []),
  'removeFromOfficialPlaylist' : IDL.Func([IDL.Text, IDL.Nat], [], []),
  'removeFromPlaylist' : IDL.Func([IDL.Text, IDL.Nat], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'searchSongs' : IDL.Func([IDL.Text], [IDL.Vec(SongView)], ['query']),
  'toggleFavorite' : IDL.Func([IDL.Nat], [IDL.Bool], []),
  'toggleLikeSong' : IDL.Func([IDL.Nat], [IDL.Nat], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const SongView = IDL.Record({
    'id' : IDL.Nat,
    'albumArt' : ExternalBlob,
    'title' : IDL.Text,
    'lyrics' : IDL.Text,
    'owner' : IDL.Principal,
    'audioFile' : ExternalBlob,
    'playCount' : IDL.Nat,
    'artist' : IDL.Text,
    'likesCount' : IDL.Nat,
    'titleImage' : ExternalBlob,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  const PlaylistView = IDL.Record({
    'name' : IDL.Text,
    'songIds' : IDL.Vec(IDL.Nat),
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addSong' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          ExternalBlob,
          ExternalBlob,
          ExternalBlob,
          IDL.Text,
        ],
        [IDL.Nat],
        [],
      ),
    'addToOfficialPlaylist' : IDL.Func([IDL.Text, IDL.Nat], [], []),
    'addToPlaylist' : IDL.Func([IDL.Text, IDL.Nat], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'clearFavorites' : IDL.Func([], [], []),
    'createOfficialPlaylist' : IDL.Func([IDL.Text], [], []),
    'createPlaylist' : IDL.Func([IDL.Text], [], []),
    'deleteSong' : IDL.Func([IDL.Nat], [], []),
    'getAllSongs' : IDL.Func([], [IDL.Vec(SongView)], ['query']),
    'getAllSongsByTitle' : IDL.Func([], [IDL.Vec(SongView)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getFavorites' : IDL.Func([], [IDL.Vec(IDL.Nat)], ['query']),
    'getOfficialPlaylist' : IDL.Func(
        [IDL.Text],
        [IDL.Opt(PlaylistView)],
        ['query'],
      ),
    'getOfficialPlaylistDetails' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(SongView)],
        ['query'],
      ),
    'getPlaylist' : IDL.Func([IDL.Text], [PlaylistView], ['query']),
    'getPlaylistDetails' : IDL.Func([IDL.Text], [IDL.Vec(SongView)], ['query']),
    'getSong' : IDL.Func([IDL.Nat], [SongView], ['query']),
    'getUserPlaylists' : IDL.Func([], [IDL.Vec(PlaylistView)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'playSong' : IDL.Func([IDL.Nat], [], []),
    'removeFromOfficialPlaylist' : IDL.Func([IDL.Text, IDL.Nat], [], []),
    'removeFromPlaylist' : IDL.Func([IDL.Text, IDL.Nat], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'searchSongs' : IDL.Func([IDL.Text], [IDL.Vec(SongView)], ['query']),
    'toggleFavorite' : IDL.Func([IDL.Nat], [IDL.Bool], []),
    'toggleLikeSong' : IDL.Func([IDL.Nat], [IDL.Nat], []),
  });
};

export const init = ({ IDL }) => { return []; };